# Generated by Django 4.2.7 on 2025-08-04 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='itemlist',
            name='Name',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready for Pickup'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='username',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='booktable',
            index=models.Index(fields=['name'], name='Base_App_bo_name_f24d49_idx'),
        ),
        migrations.AddIndex(
            model_name='booktable',
            index=models.Index(fields=['email'], name='Base_App_bo_email_0be704_idx'),
        ),
        migrations.AddIndex(
            model_name='booktable',
            index=models.Index(fields=['date'], name='Base_App_bo_date_029dd3_idx'),
        ),
        migrations.AddIndex(
            model_name='itemlist',
            index=models.Index(fields=['Name'], name='Base_App_it_Name_ea3ff7_idx'),
        ),
        migrations.AddIndex(
            model_name='items',
            index=models.Index(fields=['name'], name='Base_App_it_name_6925ed_idx'),
        ),
        migrations.AddIndex(
            model_name='items',
            index=models.Index(fields=['price'], name='Base_App_it_price_b077b4_idx'),
        ),
        migrations.AddIndex(
            model_name='items',
            index=models.Index(fields=['Category'], name='Base_App_it_Categor_f1ca58_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_name'], name='Base_App_or_custome_65af90_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_email'], name='Base_App_or_custome_d48706_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_date'], name='Base_App_or_order_d_0c3300_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='Base_App_or_status_2e5115_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['total_amount'], name='Base_App_or_total_a_865c5e_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='Base_App_or_order_i_5522d6_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product_name'], name='Base_App_or_product_1feeca_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['username'], name='Base_App_re_usernam_0c1665_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='Base_App_re_rating_83f38a_idx'),
        ),
    ]
