# Generated by Django 4.2.7 on 2025-08-04 13:15

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0004_alter_booktable_date_alter_booktable_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='email',
            field=encrypted_model_fields.fields.EncryptedEmailField(db_index=True),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='name',
            field=encrypted_model_fields.fields.EncryptedCharField(db_index=True),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='phone',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='itemlist',
            name='Name',
            field=encrypted_model_fields.fields.EncryptedCharField(db_index=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='description',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=encrypted_model_fields.fields.EncryptedCharField(db_index=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=encrypted_model_fields.fields.EncryptedIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_address',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=encrypted_model_fields.fields.EncryptedEmailField(db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=encrypted_model_fields.fields.EncryptedCharField(db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='special_instructions',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='extra_demands',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=encrypted_model_fields.fields.EncryptedCharField(db_index=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='username',
            field=encrypted_model_fields.fields.EncryptedCharField(db_index=True),
        ),
    ]
