# Generated by Django 5.2.4 on 2025-08-05 06:58

import Base_App.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0006_alter_booktable_email_alter_booktable_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='email',
            field=Base_App.encryption.EncryptedEmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='name',
            field=Base_App.encryption.EncryptedCharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='phone',
            field=Base_App.encryption.EncryptedCharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='itemlist',
            name='Name',
            field=Base_App.encryption.EncryptedCharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='items',
            name='description',
            field=Base_App.encryption.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=Base_App.encryption.EncryptedCharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=Base_App.encryption.EncryptedIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_address',
            field=Base_App.encryption.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=Base_App.encryption.EncryptedEmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=Base_App.encryption.EncryptedCharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=Base_App.encryption.EncryptedCharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='special_instructions',
            field=Base_App.encryption.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='extra_demands',
            field=Base_App.encryption.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=Base_App.encryption.EncryptedCharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=Base_App.encryption.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='username',
            field=Base_App.encryption.EncryptedCharField(db_index=True, max_length=50),
        ),
    ]
