# Generated by Django 5.2.4 on 2025-08-05 07:02

import Base_App.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0007_alter_booktable_email_alter_booktable_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='name',
            field=Base_App.encryption.EncryptedCharField(db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='phone',
            field=Base_App.encryption.EncryptedCharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='itemlist',
            name='Name',
            field=Base_App.encryption.EncryptedCharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=Base_App.encryption.EncryptedCharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=Base_App.encryption.EncryptedCharField(db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=Base_App.encryption.EncryptedCharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=Base_App.encryption.EncryptedCharField(db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='review',
            name='username',
            field=Base_App.encryption.EncryptedCharField(db_index=True, max_length=1000),
        ),
    ]
