# Generated by Django 5.2.4 on 2025-08-05 07:29

import Base_App.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0008_alter_booktable_name_alter_booktable_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='email',
            field=Base_App.encryption.EncryptedEmailField(db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=Base_App.encryption.EncryptedEmailField(db_index=True, max_length=1000),
        ),
    ]
