# Generated by Django 5.2.4 on 2025-08-06 08:31

import Base_App.encryption
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0012_alter_items_image_itemimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantityBasedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', Base_App.encryption.EncryptedCharField(db_index=True, max_length=500)),
                ('description', Base_App.encryption.EncryptedTextField(blank=True)),
                ('base_price', Base_App.encryption.EncryptedIntegerField(db_index=True, help_text='Price per unit')),
                ('category', models.CharField(choices=[('biscuits', 'Biscuits'), ('cakes', 'Cakes')], db_index=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quantity_items/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='Base_App_qu_name_a3ec1a_idx'), models.Index(fields=['base_price'], name='Base_App_qu_base_pr_9a96c6_idx'), models.Index(fields=['category'], name='Base_App_qu_categor_051c22_idx'), models.Index(fields=['is_available'], name='Base_App_qu_is_avai_0ebd8b_idx')],
            },
        ),
    ]
