# Generated by Django 5.2.4 on 2025-08-07 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0013_quantitybaseditem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuantityBasedItem',
        ),
    ]
