# Generated by Django 5.2.4 on 2025-08-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0014_delete_quantitybaseditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='email',
            field=models.EmailField(db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='name',
            field=models.CharField(db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='phone',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='special_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='extra_demands',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(db_index=True, max_length=1000),
        ),
    ]
